version: '3'

services:
  database:
    container_name: hipages-database
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: hipages
      MYSQL_DATABASE: hipages
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d

  server:
    container_name: hipages-server
    build:
      context: ./server
    environment:
      NODE_ENV: development
    links:
      - database:database
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/hipages/server
      - /usr/src/hipages/server/node_modules

  ui:
    container_name: hipages-ui
    build:
      context: ./ui
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./ui:/usr/src/hipages/ui
      - /usr/src/hipages/ui/node_modules
